#ifndef ENUMMENSAJES_H_INCLUDED
#define ENUMMENSAJES_H_INCLUDED

typedef enum {OK, NOMBRE_INVALIDO, NOMBRE_ARCHIVO_INVALIDO, NUMERO_INVALIDO, COMANDO_INVALIDO,
YA_EXISTE, NO_EXISTE_POLINOMIO, NO_INGRESO_NOMBRE, NO_INGRESO_TERMINO, PARAMETROS_INVALIDOS} TipoMensaje;

void MostrarMensaje(TipoMensaje tipo);


#endif // ENUMMENSAJES_H_INCLUDED
