#ifndef ENUMCOMANDOS_H_INCLUDED
#define ENUMCOMANDOS_H_INCLUDED

typedef enum{CREAR, SUMAR, MULTIPLICAR, EVALUAR, ES_RAIZ, MOSTRAR, GUARDAR, RECUPERAR, SALIR} EnumComandos;

#endif // ENUMCOMANDOS_H_INCLUDED
